addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.11.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.0")
